export const BACK_PATHS = {
    signIn: 'user/sign-in',
    signUp: 'user/sign-up',
    auth: 'user/auth',
    logout: 'user/log-out',
    editProfile: 'user/edit-profile',
    getPropertyById: 'properties/get/:propertyId',
    getUserProperties: 'properties/user/:userId',
    getAllOffers: 'properties/offers',
    getLastOffers: 'properties/last-offers',
    addProperty: 'properties',
    editProperty: 'properties/patch/:propertyId',
    getProfileByUserId: 'user/profile/:userId',
    getDeals: 'deals',
    signDeal: 'deals/sign/:dealId',
    cancelDeal: 'deals/cancel/:dealId',
    sendDeal: 'deals/send/:propertyId',
};